/** @type {import('tailwindcss').Config} */

const defaultTheme = require("tailwindcss/defaultTheme");
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./services/colorService.js",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "img-bug": "url('/img/bug.svg')",
        "img-dark": "url('/img/dark.svg')",
        "img-dragon": "url('/img/dragon.svg')",
        "img-electric": "url('/img/electric.svg')",
        "img-fairy": "url('/img/fairy.svg')",
        "img-fighting": "url('/img/fighting.svg')",
        "img-fire": "url('/img/fire.svg')",
        "img-flying": "url('/img/flying.svg')",
        "img-ghost": "url('/img/ghost.svg')",
        "img-grass": "url('/img/grass.svg')",
        "img-ground": "url('/img/ground.svg')",
        "img-ice": "url('/img/ice.svg')",
        "img-normal": "url('/img/normal.svg')",
        "img-poison": "url('/img/poison.svg')",
        "img-psychic": "url('/img/psychic.svg')",
        "img-rock": "url('/img/rock.svg')",
        "img-steel": "url('/img/steel.svg')",
        "img-water": "url('/img/water.svg')",
      },
      colors: {
        bug: "#449754",
        "bug-light": "#66e37e",
        dark: "#5a5979",
        "dark-light": "#9291c5",
        dragon: "#61cad9",
        "dragon-light": "#71daff",
        electric: "#e3e32b",
        "electric-light": "#fbfb72",
        fairy: "#971944",
        "fairy-light": "#ea1369",
        fighting: "#f0623a",
        "fighting-light": "#ff813d",
        fire: "#ac2024",
        "fire-light": "#f82e34",
        flying: "#4a677d",
        "flying-light": "#77a6c9",
        ghost: "#32326a",
        "ghost-light": "#5656b6",
        grass: "#48cfaf",
        "grass-light": "#1b4e42",
        ground: "#5c3d18",
        "ground-light": "#a9702c",
        ice: "#86d2f5",
        "ice-light": "#d8f0fa",
        normal: "#73525b",
        "normal-light": "#ca98a7",
        poison: "#5f2c8a",
        "poison-light": "#9b69d9",
        psychic: "#a5296c",
        "psychic-light": "#f13c9e",
        rock: "#48180b",
        "rock-light": "#943116",
        steel: "#5f756d",
        "steel-light": "#42bd94",
        water: "#1552e2",
        "water-light": "#86a8fc",
        dark1: "#2a314f",
        dark2: "#373f65",
        dark3: "#4b568b",
        dark4: "#0e111c"
      },
      fontFamily: {
        sans: ["Nunito", ...defaultTheme.fontFamily.sans],
      },
      aspectRatio: {
        "5/3": "5 / 3",
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/line-clamp"),
  ],
};
