export const colors = {
  bug: {
    dark: "bg-bug",
    light: "bg-bug-light",
    text: "text-white",
    textLight: "text-bug-light",
  },
  dark: {
    dark: "bg-dark",
    light: "bg-dark-dark",
    text: "text-white",
    textLight: "text-bug-light",
  },
  dragon: {
    dark: "bg-dragon",
    light: "bg-dragon-light",
    text: "text-white",
    textLight: "text-dragon-light",
  },
  electric: {
    dark: "bg-electric",
    light: "bg-electric-light",
    text: "text-black",
    textLight: "text-electric-light",
  },
  fairy: {
    dark: "bg-fairy",
    light: "bg-fairy-light",
    text: "text-white",
    textLight: "text-fairy-light",
  },
  fighting: {
    dark: "bg-fighting",
    light: "bg-fighting-light",
    text: "text-white",
    textLight: "text-fighting-light",
  },
  fire: {
    dark: "bg-fire",
    light: "bg-fire-light",
    text: "text-white",
    textLight: "text-fire-light",
  },
  flying: {
    dark: "bg-flying",
    light: "bg-flying-light",
    text: "text-white",
    textLight: "text-flying-light",
  },
  ghost: {
    dark: "bg-ghost",
    light: "bg-ghost-light",
    text: "text-white",
    textLight: "text-ghost-light",
  },
  grass: {
    dark: "bg-grass",
    light: "bg-grass-light",
    text: "text-white",
    textLight: "text-grass-light",
  },
  ground: {
    dark: "bg-ground",
    light: "bg-ground-light",
    text: "text-white",
    textLight: "text-ground-light",
  },
  ice: {
    dark: "bg-ice",
    light: "bg-ice-light",
    text: "text-black",
    textLight: "text-ice-light",
  },
  normal: {
    dark: "bg-normal",
    light: "bg-normal-light",
    text: "text-white",
    textLight: "text-normal-light",
  },
  poison: {
    dark: "bg-poison",
    light: "bg-poison-light",
    text: "text-white",
    textLight: "text-poison-light",
  },
  psychic: {
    dark: "bg-psychic",
    light: "bg-psychic-light",
    text: "text-white",
    textLight: "text-psychic-light",
  },
  rock: {
    dark: "bg-rock",
    light: "bg-rock-light",
    text: "text-white",
    textLight: "text-rock-light",
  },
  steel: {
    dark: "bg-steel",
    light: "bg-steel-light",
    text: "text-white",
    textLight: "text-steel-light",
  },
  water: {
    dark: "bg-water",
    light: "bg-water-light",
    text: "text-white",
    textLight: "text-water-light",
  },
};
